version: 0.0.{build}

platform:
 - x64

configuration:
 - Debug
 - Release

skip_branch_with_pr: true

clone_folder: c:\sq

before_build:
 - mkdir build
 - cd build
 - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%
 - echo %platform%
 - git submodule update --init --recursive
 - if %platform%==X64 (cmake .. -G "Visual Studio 14 2015 Win64")
 - if %platform%==x86 (cmake .. -G "Visual Studio 14 2015")

build_script:
 - cmake --build . --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
 - path: build\*\%configuration%\*.exe
 - path: build\*\%configuration%\*.dll

test: off
